model: C-Flow
backbone: wide_resnet50_2
layers: ['layer2','layer3','layer4']
fiber_batch_size: 64
decoder: freia-cflow
condition_vector: 128
coupling_blocks: 8
clamp_alpha: 1.9
permute_soft: False
lr: 0.0001
